# Output
    
Track change in capacity for every station, and when the capacity changed
    
Key-value map where the key (station name) contains a dataframe of capacity, and when capacity changed.

Output for every station is stored in a CSV

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
stations_raw = pd.read_csv('current_bluebikes_stations.csv')
tripdata_raw = pd.read_csv('202109-bluebikes-tripdata.csv')

In [3]:
stations_raw.head(3)

,Number,Name,Latitude,Longitude,District,Public,Total docks
0,K32015,1200 Beacon St,42.344149,-71.114674,Brookline,Yes,15
1,W32006,160 Arsenal,42.364664,-71.175694,Watertown,Yes,11
2,A32019,175 N Harvard St,42.363796,-71.129164,Boston,Yes,18

In [4]:
tripdata_raw.head(3)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,postal code
0,651,2021-09-01 00:00:04.0060,2021-09-01 00:10:55.9040,93,JFK/UMass T Stop,42.320340,-71.051180,296,Farragut Rd at E. 6th St,42.333400,-71.024950,6612,Customer,NaN
1,961,2021-09-01 00:00:10.2940,2021-09-01 00:16:12.2820,425,The Dimock Center,42.319309,-71.096399,55,Boylston St at Massachusetts Ave,42.347406,-71.086784,5157,Customer,95014
2,801,2021-09-01 00:00:11.1960,2021-09-01 00:13:32.4020,61,Boylston St at Fairfield St,42.348762,-71.082383,47,Cross St at Hanover St,42.362811,-71.056067,6793,Subscriber,02113

In [3]:
tripdata_raw.nunique()

tripduration                 9391
starttime                  432200
stoptime                   432199
start station id              413
start station name            413
start station latitude        413
start station longitude       413
end station id                413
end station name              413
end station latitude          413
end station longitude         413
bikeid                       3560
usertype                        2
postal code                  6453
dtype: int64

# We can't match stations based on ID - how about station name?

In [4]:
station_names = stations_raw['Name'].unique()
end_names = list(tripdata_raw['end station name'].unique())
for name in station_names:
    contains = name in end_names
    if contains == False:
        print("We dont have this name: ", name)

We dont have this name:  555 Metropolitan Ave
We dont have this name:  Graham and Parks School ? Linnaean St at Walker St
We dont have this name:  Union St at Herrick Rd ? Newton Centre Green Line

In [69]:
# lets see if we can determine station by lat/lon instead

for lat in station_lat:
    contains = lat in end_lat
    if contains == False:
        print("We dont have this name: ", lat)

We dont have this name:  42.34414899
We dont have this name:  42.36466403
We dont have this name:  42.38032335
We dont have this name:  42.38100143
We dont have this name:  42.2681
We dont have this name:  42.34178089
We dont have this name:  42.37500235
We dont have this name:  42.41143223
We dont have this name:  42.34960945
We dont have this name:  42.38078817
We dont have this name:  42.36550729
We dont have this name:  42.39841773
We dont have this name:  42.36895181
We dont have this name:  42.29167943
We dont have this name:  42.37532835
We dont have this name:  42.33664795
We dont have this name:  42.39558846
We dont have this name:  42.27881158
We dont have this name:  42.27265394
We dont have this name:  42.33047365
We dont have this name:  42.35991176
We dont have this name:  42.35533502
We dont have this name:  42.29266593
We dont have this name:  42.36277389
We dont have this name:  42.39223284
We dont have this name:  42.34805541
We dont have this name:  42.34807412
We dont have this name:  42.35711921
We dont have this name:  42.3991826
We dont have this name:  42.33006232
We dont have this name:  42.35082681
We dont have this name:  42.3382668
We dont have this name:  42.28634589
We dont have this name:  42.28611421
We dont have this name:  42.39319611
We dont have this name:  42.38353252
We dont have this name:  42.38522394
We dont have this name:  42.37207658
We dont have this name:  42.36608797
We dont have this name:  42.36435589
We dont have this name:  42.27462067
We dont have this name:  42.31786021
We dont have this name:  42.33987892
We dont have this name:  42.34776345
We dont have this name:  42.37331213
We dont have this name:  42.35656092
We dont have this name:  42.33639915
We dont have this name:  42.30785224
We dont have this name:  42.35204262
We dont have this name:  42.35114198
We dont have this name:  42.3501061
We dont have this name:  42.34958942
We dont have this name:  42.34465063
We dont have this name:  42.34740621
We dont have this name:  42.33462893
We dont have this name:  42.34894857
We dont have this name:  42.36154571
We dont have this name:  42.35849449
We dont have this name:  42.3983606
We dont have this name:  42.3951715
We dont have this name:  42.39453079
We dont have this name:  42.40994213
We dont have this name:  42.39648358
We dont have this name:  42.41034691
We dont have this name:  42.38614141
We dont have this name:  42.33376473
We dont have this name:  42.33274392
We dont have this name:  42.37408991
We dont have this name:  42.36514871
We dont have this name:  42.37119728
We dont have this name:  42.36125722
We dont have this name:  42.36530095
We dont have this name:  42.39813565
We dont have this name:  42.37544913
We dont have this name:  42.28277901
We dont have this name:  42.28633199
We dont have this name:  42.35574335
We dont have this name:  42.36079297
We dont have this name:  42.36455361
We dont have this name:  42.37412455
We dont have this name:  42.39022671
We dont have this name:  42.40328057
We dont have this name:  42.39636528
We dont have this name:  42.37228487
We dont have this name:  42.34366582
We dont have this name:  42.29704126
We dont have this name:  42.35159662
We dont have this name:  42.33554308
We dont have this name:  42.36070284
We dont have this name:  42.34011512
We dont have this name:  42.33023071
We dont have this name:  42.34474225
We dont have this name:  42.35169202
We dont have this name:  42.35154735
We dont have this name:  42.34024645
We dont have this name:  42.34922469
We dont have this name:  42.34835863
We dont have this name:  42.39407224
We dont have this name:  42.36041775
We dont have this name:  42.3510045
We dont have this name:  42.38363895
We dont have this name:  42.37207611
We dont have this name:  42.34992828
We dont have this name:  42.38830554
We dont have this name:  42.32784317
We dont have this name:  42.36178044
We dont have this name:  42.35096144
We dont have this name:  42.34924377
We dont have this name:  42.39790817
We dont have this name:  42.34404051
We dont have this name:  42.32984299
We dont have this name:  42.38762811
We dont have this name:  42.38717463
We dont have this name:  42.38952436
We dont have this name:  42.39329263
We dont have this name:  42.40725945
We dont have this name:  42.35339051
We dont have this name:  42.35276621
We dont have this name:  42.29963349
We dont have this name:  42.3930184
We dont have this name:  42.39108438
We dont have this name:  42.30412793
We dont have this name:  42.38267828
We dont have this name:  42.36300378
We dont have this name:  42.28297568
We dont have this name:  42.31886468
We dont have this name:  42.41427294
We dont have this name:  42.38240378
We dont have this name:  42.37057753
We dont have this name:  42.3598254
We dont have this name:  42.3829443
We dont have this name:  42.39638681
We dont have this name:  42.41496265
We dont have this name:  42.3494261
We dont have this name:  42.34521562
We dont have this name:  42.34953017
We dont have this name:  42.3722168
We dont have this name:  42.34435176
We dont have this name:  42.36599433
We dont have this name:  42.36920617
We dont have this name:  42.32464511
We dont have this name:  42.33741748
We dont have this name:  42.3602737
We dont have this name:  42.33658555
We dont have this name:  42.38165061
We dont have this name:  42.26286746
We dont have this name:  42.29606705
We dont have this name:  42.32176526
We dont have this name:  42.37426714
We dont have this name:  42.36371276
We dont have this name:  42.32293117
We dont have this name:  42.30604563
We dont have this name:  42.34655124
We dont have this name:  42.32033974
We dont have this name:  42.40616124
We dont have this name:  42.36356016
We dont have this name:  42.36242784
We dont have this name:  42.36955298
We dont have this name:  42.29376656
We dont have this name:  42.51142784
We dont have this name:  42.36346469
We dont have this name:  42.34369056
We dont have this name:  42.34734473
We dont have this name:  42.38674802
We dont have this name:  42.40935396
We dont have this name:  42.3572185
We dont have this name:  42.3977834
We dont have this name:  42.37487847
We dont have this name:  42.33978053
We dont have this name:  42.38066931
We dont have this name:  42.36135838
We dont have this name:  42.41420213
We dont have this name:  42.40726052
We dont have this name:  42.39120972
We dont have this name:  42.34135616
We dont have this name:  42.33949454
We dont have this name:  42.36884408
We dont have this name:  42.36774122
We dont have this name:  42.5180352
We dont have this name:  42.38042947
We dont have this name:  42.36054174
We dont have this name:  42.36085937
We dont have this name:  42.3595732
We dont have this name:  42.36213123
We dont have this name:  42.35560121
We dont have this name:  42.32143814
We dont have this name:  42.28072514
We dont have this name:  42.37478629
We dont have this name:  42.28484472
We dont have this name:  42.35553628
We dont have this name:  42.36769018
We dont have this name:  42.35732922
We dont have this name:  42.32206566
We dont have this name:  42.33620337
We dont have this name:  42.36762049
We dont have this name:  42.36068456
We dont have this name:  42.29118035
We dont have this name:  42.35766248
We dont have this name:  42.35847764
We dont have this name:  42.3339227
We dont have this name:  42.36224179
We dont have this name:  42.36161932
We dont have this name:  42.40715656
We dont have this name:  42.35182807
We dont have this name:  42.29442579
We dont have this name:  42.38815705
We dont have this name:  42.37927325
We dont have this name:  42.3650112
We dont have this name:  42.36411904
We dont have this name:  42.35585436
We dont have this name:  42.34652004
We dont have this name:  42.41608484
We dont have this name:  42.34827839
We dont have this name:  42.36575798
We dont have this name:  42.29116853
We dont have this name:  42.28630716
We dont have this name:  42.31787329
We dont have this name:  42.33624445
We dont have this name:  42.32760387
We dont have this name:  42.52189284
We dont have this name:  42.52345239
We dont have this name:  42.50182399
We dont have this name:  42.53466911
We dont have this name:  42.35317809
We dont have this name:  42.34881026
We dont have this name:  42.35148193
We dont have this name:  42.36860524
We dont have this name:  42.34854543
We dont have this name:  42.51836788
We dont have this name:  42.35775309
We dont have this name:  42.349496
We dont have this name:  42.39239749
We dont have this name:  42.36426344
We dont have this name:  42.39189812
We dont have this name:  42.39044949
We dont have this name:  42.27748444
We dont have this name:  42.34619708
We dont have this name:  42.34954403
We dont have this name:  42.38445226
We dont have this name:  42.40833706
We dont have this name:  42.3529457
We dont have this name:  42.41250451
We dont have this name:  42.32039374
We dont have this name:  42.3329529
We dont have this name:  42.40231703
We dont have this name:  42.31930943
We dont have this name:  42.34679008
We dont have this name:  42.28621295
We dont have this name:  42.36544486
We dont have this name:  42.40016805
We dont have this name:  42.35668335
We dont have this name:  42.3388956
We dont have this name:  42.34254914
We dont have this name:  42.37971603
We dont have this name:  42.32956868
We dont have this name:  42.31218918
We dont have this name:  42.36264779
We dont have this name:  42.31727474
We dont have this name:  42.31869734
We dont have this name:  42.36473899
We dont have this name:  42.38536765
We dont have this name:  42.37250865
We dont have this name:  42.33595898
We dont have this name:  42.31242399
We dont have this name:  42.40933007
We dont have this name:  42.29916498
We dont have this name:  42.34895285
We dont have this name:  42.35389024
We dont have this name:  42.28072815
We dont have this name:  42.34286835
We dont have this name:  42.28198628
We dont have this name:  42.33833424
We dont have this name:  42.33509899
We dont have this name:  42.38170676
We dont have this name:  42.34303291
We dont have this name:  42.3385146
We dont have this name:  42.35145812
We dont have this name:  42.2771947
We dont have this name:  42.34157472
We dont have this name:  42.351586
We dont have this name:  42.36526032
We dont have this name:  42.33758601
We dont have this name:  42.36590788
We dont have this name:  42.3496005
We dont have this name:  42.34947178
We dont have this name:  42.36178741
We dont have this name:  42.33286288
We dont have this name:  42.38567579

# Summary: ID's from trip data and station database don't match.

# Best thing we can do is match by station name (only 3/413 stations don't match using this method)

In [102]:
# remake our dictionary
cols = ["time", "capacity"]
station_names = stations_raw['Name'].unique()
stations_dict = {}

for id in station_names:
    dock_capacity = stations_raw.loc[stations_raw['Name'] == id]['Total docks']
    # 
    stations_dict[id] = pd.DataFrame(columns = cols)
    stations_dict[id]["capacity"] = dock_capacity
    stations_dict[id]["time"] = "0"
    
   
# remake our global dictionary
cols = ["time", "capacity", "station", "increment", "decrement", "wait_time", "year", "month", "day_of_week", "day", "hour", "minute", "second"]
stations_dict_all = {}

stations_dict_all["key"] = pd.DataFrame(columns = cols)
# stations_dict_all["key"]["capacity"] = dock_capacity
# stations_dict_all["key"]["time"] = "0"
# stations_dict_all["key"]["station"] = "0"
# stations_dict_all["key"]["increment"] = 0
# stations_dict_all["key"]["decrement"] = 0

In [103]:
stations_dict_all["key"]

Empty DataFrame
Columns: [time, capacity, station, increment, decrement, wait_time, year, month, day_of_week, day, hour, minute, second]
Index: []

In [104]:
stations_dict["1200 Beacon St"]

  time  capacity
0    0        15

In [31]:
tripdata_raw.shape[0] # rows in trip data

432254

In [64]:
import datetime
from pytz import timezone

print ('Current date/time: {}'.format(datetime.datetime.now()))

Current date/time: 2021-11-16 19:50:48.089884

In [90]:
now = datetime.datetime.now()
(now-datetime_obj).total_seconds()

6492937.61919

In [91]:
now2 = datetime.datetime.now()
(now2-now).total_seconds()

24.776428

In [84]:
#date_time_str = 'Jun 28 2018 7:40AM'
# date_time_str = '9/1/2021  11:14:47.222 PM'

# date_format_string = '%m/%d/%Y %I:%M:%S.%f %p'


date_time_str = '2021-09-01 00:00:10.2940'
date_format_string = '%Y-%m-%d %H:%M:%S.%f'
datetime_obj = datetime.datetime.strptime(date_time_str, date_format_string)

print('Date:', datetime_obj.year)
print('Time:', datetime_obj.month)
print('Date:', datetime_obj.day)
print('Time:', datetime_obj.hour)
print('Time:', datetime_obj.minute)
print('Time:', datetime_obj.second)
print('Time:', datetime_obj.microsecond)
print('Date-time:', datetime_obj)



datetime_obj = timezone('UTC').localize(date_time_obj)
print('Date:', datetime_obj.year)
print('Time:', datetime_obj.month)
print('Date:', datetime_obj.day)
print('Time:', datetime_obj.hour)
print('Time:', datetime_obj.minute)
print('Time:', datetime_obj.second)
print('Date-time:', datetime_obj)


datetime_obj = datetime_obj.astimezone(timezone('US/Eastern'))
print('Date:', datetime_obj.year)
print('Time:', datetime_obj.month)
print('Date:', datetime_obj.day)
print('Time:', datetime_obj.hour)
print('Time:', datetime_obj.minute)
print('Time:', datetime_obj.second)
print('Date-time:', datetime_obj)
print('Date-time:', datetime_obj.strftime("%A"))

Date: 2021
Time: 9
Date: 1
Time: 0
Time: 0
Time: 10
Time: 294000
Date-time: 2021-09-01 00:00:10.294000
Date: 2021
Time: 9
Date: 1
Time: 23
Time: 14
Time: 47
Date-time: 2021-09-01 23:14:47+00:00
Date: 2021
Time: 9
Date: 1
Time: 19
Time: 14
Time: 47
Date-time: 2021-09-01 19:14:47-04:00
Date-time: Wednesday

In [77]:

date_time_str = '2021-09-01 00:00:10.2940'
date_format_string = '%Y-%m-%d %H:%M:%S.%f'

In [105]:
incoming_prev = None
departing_prev = None
wait_time_incoming=0
wait_time_departing=0

for i in range(tripdata_raw.shape[0]):
    if i==0:
        continue
    if i % 1000 == 0:
        print(i)
    trip = tripdata_raw.iloc[i]
    #print(trip)
    start_name = trip['start station name']
    start_time = trip['starttime']
    #print(start_time)
    # adjust station capacity
    if start_name in stations_dict:
        curr_cap = stations_dict[start_name]["capacity"].iloc[-1] # get last row
        stations_dict[start_name] = stations_dict[start_name].append({"time": start_time, "capacity": curr_cap-1}, ignore_index=True)
        
        # date and time operations
        datetime_obj = datetime.datetime.strptime(start_time, date_format_string)
#         if departing_prev != None:
#             wait_time_departing = (datetime_obj-departing_prev).total_seconds()
#         departing_prev = datetime_obj
#         datetime_obj = timezone('UTC').localize(date_time_obj)
#         datetime_obj = datetime_obj.astimezone(timezone('US/Eastern'))
        stations_dict_all["key"] = stations_dict_all["key"].append({"time": start_time, "capacity": curr_cap-1, "station": start_name, "increment": 0, "decrement": 1, "wait_time": wait_time_departing, "year": datetime_obj.year, "month": datetime_obj.month, "day_of_week": datetime_obj.strftime("%A"), "day": datetime_obj.day, "hour": datetime_obj.hour, "minute": datetime_obj.minute, "second": datetime_obj.second}, ignore_index=True)

    
    end_name = trip['end station name']
    end_time = trip['stoptime']

    if end_name in stations_dict:
        curr_cap = stations_dict[end_name]["capacity"].iloc[-1] # get last row
        #print(curr_cap)
        stations_dict[end_name] = stations_dict[end_name].append({"time": end_time, "capacity": curr_cap+1}, ignore_index=True)
        
        # date and time operations
        datetime_obj = datetime.datetime.strptime(end_time, date_format_string)
#         if incoming_prev != None:
#             wait_time_incoming = (datetime_obj-incoming_prev).total_seconds()
#         incoming_prev = datetime_obj
#         datetime_obj = timezone('UTC').localize(date_time_obj)
#         datetime_obj = datetime_obj.astimezone(timezone('US/Eastern'))
        stations_dict_all["key"] = stations_dict_all["key"].append({"time": end_time, "capacity": curr_cap+1, "station": end_name, "increment": 1, "decrement": 0, "wait_time": wait_time_incoming, "year": datetime_obj.year, "month": datetime_obj.month, "day_of_week": datetime_obj.strftime("%A"), "day": datetime_obj.day, "hour": datetime_obj.hour, "minute": datetime_obj.minute, "second": datetime_obj.second}, ignore_index=True)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000
373000
374000
375000
376000
377000
378000
379000
380000
381000
382000
383000
384000
385000
386000
387000
388000
389000
390000
391000
392000
393000
394000
395000
396000
397000
398000
399000
400000
401000
402000
403000
404000
405000
406000
407000
408000
409000
410000
411000
412000
413000
414000
415000
416000
417000
418000
419000
420000
421000
422000
423000
424000
425000
426000
427000
428000
429000
430000
431000
432000

In [107]:
stations_dict_all["key"][stations_dict_all["key"]["station"] == "1200 Beacon St"]

,time,capacity,station,increment,decrement,wait_time,year,month,day_of_week,day,hour,minute,second
225,2021-09-01 00:07:38.0940,14,1200 Beacon St,0,1,0,2021,9,Wednesday,1,0,7,38
267,2021-09-01 00:09:02.4160,13,1200 Beacon St,0,1,0,2021,9,Wednesday,1,0,9,2
459,2021-09-01 00:30:10.0210,14,1200 Beacon St,1,0,0,2021,9,Wednesday,1,0,30,10
1561,2021-09-01 01:19:51.0640,15,1200 Beacon St,1,0,0,2021,9,Wednesday,1,1,19,51
1658,2021-09-01 01:12:53.7920,14,1200 Beacon St,0,1,0,2021,9,Wednesday,1,1,12,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859588,2021-09-30 22:48:42.9650,-4,1200 Beacon St,1,0,0,2021,9,Thursday,30,22,48,42
860086,2021-09-30 23:00:37.6920,-3,1200 Beacon St,1,0,0,2021,9,Thursday,30,23,0,37
860339,2021-09-30 23:16:36.3850,-2,1200 Beacon St,1,0,0,2021,9,Thursday,30,23,16,36
861555,2021-09-30 23:37:08.5160,-3,1200 Beacon St,0,1,0,2021,9,Thursday,30,23,37,8
862093,2021-10-01 01:01:13.6380,-2,1200 Beacon St,1,0,0,2021,10,Friday,1,1,1,13

In [32]:
for i in range(tripdata_raw.shape[0]):
    if i==0:
        continue
    if i % 1000 == 0:
        print(i)
    trip = tripdata_raw.iloc[i]
    #print(trip)
    start_name = trip['start station name']
    start_time = trip['starttime']
    
    # adjust station capacity
    if start_name in stations_dict:
        curr_cap = stations_dict[start_name]["capacity"].iloc[-1] # get last row
        stations_dict[start_name] = stations_dict[start_name].append({"time": start_time, "capacity": curr_cap-1}, ignore_index=True)
    
    end_name = trip['end station name']
    end_time = trip['stoptime']

    if end_name in stations_dict:
        curr_cap = stations_dict[end_name]["capacity"].iloc[-1] # get last row
        #print(curr_cap)
        stations_dict[end_name] = stations_dict[end_name].append({"time": end_time, "capacity": curr_cap+1}, ignore_index=True)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000
373000
374000
375000
376000
377000
378000
379000
380000
381000
382000
383000
384000
385000
386000
387000
388000
389000
390000
391000
392000
393000
394000
395000
396000
397000
398000
399000
400000
401000
402000
403000
404000
405000
406000
407000
408000
409000
410000
411000
412000
413000
414000
415000
416000
417000
418000
419000
420000
421000
422000
423000
424000
425000
426000
427000
428000
429000
430000
431000
432000

# Save each station data as CSV

In [41]:
for station in stations_dict:
    st = station
    if '/' in st:
        st = st.replace('/', '-slash-')
    if '?' in st:
        st = st.replace('?', '-ques-')
    stations_dict[station].to_csv('202109-stations-capacity/' + st + '.csv', index=False)

1200 Beacon St
160 Arsenal
175 N Harvard St
191 Beacon St
2 Hummingbird Lane at Olmsted Green
30 Dane St
359 Broadway - Broadway at Fayette Street
555 Metropolitan Ave
606 American Legion Hwy at Canterbury St
645 Summer St
699 Mt Auburn St
7 Acre Park
700 Commonwealth Ave.
700 Huron Ave
75 Binney St
84 Cambridgepark Dr
855 Broadway
955 Mass Ave
Adams Branch Library
Adams St at Lonsdale St
Airport T Stop - Bremen St at Brooks St
Albany St at E. Brookline St
Alewife MBTA at Steel Place
Alewife Station at Russell Field
American Legion Hwy at Cummins Hwy
American Legion Hwy at Hyde Park Ave
Ames St at Broadway
Ames St at Main St
Andrew T Stop - Dorchester Ave at Dexter St
Aquarium T Stop - 200 Atlantic Ave
Arch St at Franklin St
Archdale Rd at Washington St
Arsenal Yards
Ashmont T Stop
Assembly Square T
Auburndale
B.U. Central - 725 Comm. Ave.
Back Bay T Stop - Dartmouth St at Stuart St
Bacon St at Washington St
Ball Sq
Bartlett St at John Elliot Sq
Beacon at Walnut
Beacon St at Charles St
Beacon St at Massachusetts Ave
Beacon St at Tappan St
Beacon St at Washington / Kirkland
Belgrade Ave at Walworth St
Bellevue T Stop
Bellingham Square
Bennington St at Byron St
Bennington St at Constitution Beach
Berkshire Street at Cambridge Street
Binney St / Sixth St
Blossom St at Charles St
Blue Hill Ave at Almont St
Blue Hill Ave at Havelock St
Blue Hill Ave at Southwood St
Boston City Hall - 28 State St
Boston College T
Boston Convention and Exhibition Center - Summer St at West Side Dr
Boston East - 126 Border St
Boston Landing
Boston Medical Center - E Concord St at Harrison Ave
Bowdoin St at Quincy St
Boylston St at Arlington St
Boylston St at Berkeley St
Boylston St at Dartmouth St
Boylston St at Exeter St
Boylston St at Fairfield St
Boylston St at Jersey St
Boylston St at Massachusetts Ave
Brigham Circle - Francis St at Huntington Ave
Brighton Center - Washington St at Cambridge St
Brighton Mills - 370 Western Ave
Broad St at Central St
Broadway at Beacham St
Broadway at Central St
Broadway at Gerrish Ave
Broadway at Grafton St
Broadway at Lynde St
Broadway at Maple St
Broadway St at Mt Pleasant St
Brookline Town Hall
Brookline Village - Station Street at MBTA
Bunker Hill Community College
Burlington Ave at Brookline Ave
California at Chapel
Cambridge Dept. of Public Works -147 Hampshire St.
Cambridge Main Library at Broadway / Trowbridge St
Cambridge St - at Columbia St / Webster Ave
Cambridge St at Joy St
CambridgeSide Galleria - CambridgeSide PL at Land Blvd
Canal St at Causeway St
Cary Square
Central Sq Post Office / Cambridge City Hall at Mass Ave / Pleasant St
Central Square at Mass Ave / Essex St
Central Square East Boston
Centre St at Parkway YMCA
Centre St at Seaverns Ave
Centre St at W. Roxbury Post Office
Centre St at Washington St
Charles Circle - Charles St at Cambridge St
Charles River Greenway - California St. at Fifth Ave
Charlestown Navy Yard
Chelsea Square
Chelsea St at Vine St
Chelsea Station
Child St at North St
Chinatown Gate Plaza
Chinatown T Stop
Christian Science Plaza - Massachusetts Ave at Westland Ave
Circuit Drive at American Legion Hwy
Clarendon Hill at Broadway
Clarendon St at Newbury St
Cleary Sq
Cleveland Circle
Clinton St at North St
Codman Square Library
Colleges of the Fenway - Fenway at Avenue Louis Pasteur
Columbia Rd at Ceylon St
Columbia Rd at Tierney Community Center
Columbus Ave at W. Canton St
Commonwealth Ave at Agganis Way
Commonwealth Ave At Babcock St
Commonwealth Ave at Chiswick Rd
Commonwealth Ave at Griggs St
Commonwealth Ave at Kelton St
Community Path at Cedar Street
Community Path at Lowell St
Concord Ave at Spinelli Place
Congress St at Boston City Hall
Congress St at Northern Ave
Congress St at Sleeper St
Conway Park - Somerville Avenue
Coolidge Corner - Beacon St at Centre St
Coolidge Sq.
Copley Square - Dartmouth St at Boylston St
Craigie at Summer St
Cross St at Hanover St
Curtis Hall - South St at Centre St
Cypress St at Clark Playground
Dana Park
Danehy Park
Danehy Park at New Street
Dartmouth St at Newbury St
Davis Square
Day Sq
Deerfield St at Commonwealth Ave
Discovery Park - 30 Acorn Park Drive
Dorchester Ave at Gillette Park
Dudley Square - Bolling Building
E Cottage St at Columbia Rd
East Boston Neighborhood Health Center - 20 Maverick Square
East Somerville Library (Broadway and Illinois)
Edgerly Education Center
Edwards Playground - Main St at Eden St
EF - North Point Park
Egleston Square - Atherton St at Washington St
Elm St at White St
Encore
Everett Square (Broadway at Chelsea St)
Fan Pier
Faneuil St at Arlington St
Farragut Rd at E. 6th St
Fields Corner T Stop
Foley St at Grand Union Blvd
Forest Hills
Foss Park
Four Corners - 157 Washington St
Franklin Park - Seaver St at Humboldt Ave
Franklin Park Zoo - Franklin Park Rd at Blue Hill Ave
Fresh Pond Reservation
Galileo Galilei Way at Main Street
Gallivan Blvd at Adams St
Geiger Gibson Community Health Center
Glendale Square (Ferry St at Broadway)
Glendon St at Condor St
Gove St at Orleans St
Government Center - Cambridge St at Court St
Graham and Parks School ? Linnaean St at Walker St
Green Street T Stop - Green St at Amory St
Grove Hall Library - 41 Geneva Ave
Grove St at Community Path
Hale Park
Harrison Ave at Bennet St
Harrison Ave at E. Dedham St
Harrison Ave at Mullins Way
Harvard Ave at Brainerd Rd
Harvard Kennedy School at Bennett St / Eliot St
Harvard Law School at Mass Ave / Jarvis St
Harvard Square at Brattle St / Eliot St
Harvard Square at Mass Ave/ Dunster
Harvard St and Stedman St
Harvard St at Greene-Rose Heritage Park
Harvard Stadium: N. Harvard St at Soldiers Field Rd
Harvard University / SEAS Cruft-Pierce Halls at 29 Oxford St
Harvard University Gund Hall at Quincy St / Kirkland St
Harvard University Housing - 115 Putnam Ave at Peabody Terrace
Harvard University Radcliffe Quadrangle at Shepard St / Garden St
Harvard University River Houses at DeWolfe St / Cowperthwaite St
Hayes Square - Vine St at Moulton St
High St at Cypress St
HMS/HSPH - Avenue Louis Pasteur at Longwood Ave
Honan Library
Huntington Ave at Mass Art
Huron Ave At Vassal Lane
Hyde Park Ave at Arlington St
Hyde Park Ave at Walk Hill St
Hyde Square - Barbara St at Centre St
ID Building East
ID Building West
Ink Block - Harrison Ave at Herald St
Inman Square at Springfield St.
Innovation Lab - 125 Western Ave at Batten Way
Jackson Square T Stop
Jamaica St at South St
JFK Crossing at Harvard St. / Thorndike St.
JFK/UMass T Stop
Kearins Playground
Kendall Street
Kendall T
Kenmore Square
Kennedy-Longfellow School 158 Spring St
Knoll St at Centre St
Lafayette at Leach St
Lafayette Square at Mass Ave / Main St / Columbia St
Landmark Center - Brookline Ave at Park Dr
Langley Lot
Lansdowne T Stop
Lechmere Station at Cambridge St / First St
Lesley University
Lewis Wharf at Atlantic Ave
Linear Park - Mass. Ave. at Cameron Ave.
Linwood St at Minuteman Bikeway
Longwood Ave at Binney St
Lower Cambridgeport at Magazine St / Riverside Rd
Magoun Square at Trum Field
Main St at Austin St
Main St at Baldwin St
Main St at Thompson Sq
Marion St at Harvard St
Marion St at White St
Martha Eliot Health Center
Mass Ave at Albany St
Mass Ave at Broadway
Mass Ave at Grafton St
Mass Ave at Hadley/Walden
Mass Ave T Station
Massachusetts Ave at Columbus Ave
Mattapan Library
Mattapan T Stop
Maverick Square - Lewis Mall
Maverick St at Massport Path
Mayor Salvo Path at Mill St
Medford St at Charlestown BCYF
MIT at Mass Ave / Amherst St
MIT Carleton St at Amherst St
MIT Hayward St at Amherst St
MIT Pacific St at Purrington St
MIT Stata Center at Vassar St / Main St
MIT Vassar St
MLK Blvd at Washington St
Morton St at Gallivan Blvd
Morton St T
Mt Auburn
Mt. Hope St at Hyde Park Ave
Mugar Way at Beacon St
Murphy Skating Rink - 1880 Day Blvd
Museum of Science
Nashua Street at Red Auerbach Way
NCAAA - Walnut Ave at Crawford St
New Balance - 20 Guest St
Newbury St at Hereford St
Newmarket Square T Stop - Massachusetts Ave at Newmarket Square
Newton Highlands T
Newton Library
Nichols Ave. at Watertown Greenway
Nonantum Library
Northbourne Rd at Hyde Park Ave
Northeastern University - North Parking Lot
Oak Square - 615 Washington St
Old Morse Park at Putnam Ave
One Beacon St
One Brigham Circle
One Broadway / Kendall Sq at Main St / 3rd St
One Kendall Square at Hampshire St / Portland St
One Memorial Drive
Orient Heights T Stop - Bennington St at Saratoga St
Orr Sq (Shirley Ave)
Packard Ave at Powderhouse Blvd
Packard's Corner - Commonwealth Ave at Brighton Ave
Park Dr at Buswell St
Park Plaza at Charles St S.
Park St at Norwell St
Pearl St at Medford St
Perry Park
Piers Park
Porter Square Station
Porzio Park
Post Office Square
Powder House Circle - Nathan Tufts Park
Prudential Center - 101 Huntington Ave
Purchase St at Pearl St
Railroad Lot and Minuteman Bikeway
Revere City Hall
Revere Public Library

Rindge Avenue - O'Neill Library
Ring Rd
Rogers St & Land Blvd
Roseland St At Dorchester Ave
Roslindale Village - South St
Roslindale Village - Washington St
Rowes Wharf at Atlantic Ave
Roxbury Crossing T Stop - Columbus Ave at Tremont St
Roxbury YMCA - Warren St at MLK Blvd
Ruggles T Stop - Columbus Ave at Melnea Cass Blvd
Ryan Playground - Dorchester Ave at Harbor View St
S Huntington Ave at Heath St
Salem Ferry Landing
Salem MBTA - Washington at Federal St
Salem State University - Bike Path at Loring Ave
Salem Willows Park
Savin Hill T Stop - S Sydney St at Bay St
Seaport Blvd at Sleeper St
Seaport Hotel - Congress St at Seaport Ln
Seaport Square - Seaport Blvd at Northern Ave
Sennott Park Broadway at Norfolk Street
Shawmut Ave at Oak St W
Shawmut T Stop
Shetland Park - Congress at Peabody St
Sidney Research Campus/Erie Street at Waverly
Silber Way
Smith Pl at Wilson Rd
Soldiers Field Park - 111 Western Ave
Somerville City Hall
Somerville City Hall Annex
Somerville Hospital
South Boston Library - 646 E Broadway
South End Library - Tremont St at W Newton St
South Station - 700 Atlantic Ave
Spaulding Rehabilitation Hospital - Charlestown Navy Yard
Spring St at Powell St
St Mary's
State Street at Channel Center
Stony Brook T Stop
Stuart St at Berkeley St
Stuart St at Charles St
Sullivan Square
Sumner St at Shirley Ave
Surface Rd at India St
Surface Rd at Summer St
Swan St. Park
Sydney St at Carson St
Talbot Ave At Blue Hill Ave
Tappan St at Brookline Hills MBTA
Teele Square
The Dimock Center
The Eddy - New St at Sumner St
The Lawn on D
The Overlook at St. Gabriel's
Thetford Ave at Norfolk St
Third at Binney
Thorndike Field at Minuteman Bikeway
Tremont St at E Berkeley St
Tremont St at Hamilton Pl
Tremont St at Northampton St
Tremont St at W. Dedham St
Tremont St at West St
Troy Boston
Union Square - Brighton Ave at Cambridge St
Union Square - Somerville
Union Square East
Union St at Herrick Rd ? Newton Centre Green Line
University of Massachusetts Boston - Campus Center
University Park
Uphams Corner
Uphams Corner T Stop - Magnolia St at Dudley St
Valenti Way at Haverhill St
Vassal Lane at Tobin/VLUS
Verizon Innovation Hub 10 Ware Street
W Broadway at D St
W Broadway at Dorchester St
Walnut Ave at School St
Walnut Ave at Warren St
Warren St at Chelsea St
Wasgott Playground
Washington St at Bowdoin St
Washington St at Brock St
Washington St at Crafts St
Washington St at Denton Terr
Washington St at Egremont Rd
Washington St at Fuller St
Washington St at Griggs Rd
Washington St at Lenox St
Washington St at Melnea Cass Blvd
Washington St at Myrtle St
Washington St at Peters Park
Washington St at Rutland St
Washington St at Talbot Ave
Washington St at Walnut St
Washington St at Walsh Playground
Washington St at Waltham St
Watermark Seaport - Boston Wharf Rd at Seaport Blvd
Watertown Sq
Watertown Town Hall
Wentworth Institute of Technology - Huntington Ave at Vancouver St
West End Park
West Newton
West Newton Armory
Western Ave at Richardson St
Whittier St Health Center
Williams St at Washington St
Wilson Square

In [155]:
station_data.index[0]

459

In [175]:
pd_all_data.at[701,'wait_time']=-99

In [177]:
pd_all_data.loc[701]

time           2021-09-01 00:29:49.8310
capacity                             16
station                   Wilson Square
increment                             1
decrement                             0
wait_time                           -99
year                               2021
month                                 9
day_of_week                   Wednesday
day                                   1
hour                                  0
minute                               29
second                               49
Name: 701, dtype: object

In [187]:
pd_all_data.sort_values('time')

,time,capacity,station,increment,decrement,wait_time,year,month,day_of_week,day,hour,minute,second
0,2021-09-01 00:00:10.2940,15,The Dimock Center,0,1,0,2021,9,Wednesday,1,0,0,10
2,2021-09-01 00:00:11.1960,18,Boylston St at Fairfield St,0,1,0,2021,9,Wednesday,1,0,0,11
4,2021-09-01 00:00:11.3700,17,Boylston St at Fairfield St,0,1,0,2021,9,Wednesday,1,0,0,11
6,2021-09-01 00:00:13.3470,14,Congress St at Northern Ave,0,1,0,2021,9,Wednesday,1,0,0,13
8,2021-09-01 00:00:21.1900,24,Inman Square at Springfield St.,0,1,0,2021,9,Wednesday,1,0,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721637,2021-10-03 21:45:24.9410,105,E Cottage St at Columbia Rd,1,0,0,2021,10,Sunday,3,21,45,24
133189,2021-10-04 00:28:07.4700,13,Christian Science Plaza - Massachusetts Ave at...,1,0,0,2021,10,Monday,4,0,28,7
443241,2021-10-04 10:05:12.1130,27,Boston Landing,1,0,0,2021,10,Monday,4,10,5,12
838535,2021-10-04 12:41:33.1680,25,Government Center - Cambridge St at Court St,1,0,0,2021,10,Monday,4,12,41,33
694091,2021-10-04 15:45:57.8570,46,Grove St at Community Path,1,0,0,2021,10,Monday,4,15,45,57

In [197]:
stations_dict_all["key"] = stations_dict_all["key"].sort_values('time')
stations_dict_all["key"]

,time,capacity,station,increment,decrement,wait_time,year,month,day_of_week,day,hour,minute,second
0,2021-09-01 00:00:10.2940,15,The Dimock Center,0,1,0,2021,9,Wednesday,1,0,0,10
2,2021-09-01 00:00:11.1960,18,Boylston St at Fairfield St,0,1,0,2021,9,Wednesday,1,0,0,11
4,2021-09-01 00:00:11.3700,17,Boylston St at Fairfield St,0,1,0,2021,9,Wednesday,1,0,0,11
6,2021-09-01 00:00:13.3470,14,Congress St at Northern Ave,0,1,0,2021,9,Wednesday,1,0,0,13
8,2021-09-01 00:00:21.1900,24,Inman Square at Springfield St.,0,1,0,2021,9,Wednesday,1,0,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721637,2021-10-03 21:45:24.9410,105,E Cottage St at Columbia Rd,1,0,0,2021,10,Sunday,3,21,45,24
133189,2021-10-04 00:28:07.4700,13,Christian Science Plaza - Massachusetts Ave at...,1,0,0,2021,10,Monday,4,0,28,7
443241,2021-10-04 10:05:12.1130,27,Boston Landing,1,0,0,2021,10,Monday,4,10,5,12
838535,2021-10-04 12:41:33.1680,25,Government Center - Cambridge St at Court St,1,0,0,2021,10,Monday,4,12,41,33
694091,2021-10-04 15:45:57.8570,46,Grove St at Community Path,1,0,0,2021,10,Monday,4,15,45,57

In [199]:
pd_all_data = stations_dict_all["key"]
#pd_all_data = pd_all_data.sort_values('time')
for sn in station_names:
    station_data = pd_all_data[pd_all_data['station']==sn]
    station_data = station_data[station_data['increment'] == 1]    
    
    indices = station_data.index
    
    for i in range(len(station_data)-1):
        row_now = station_data.iloc[i]
        row_next = station_data.iloc[i+1]
        date_now = datetime.datetime.strptime(row_now["time"], date_format_string)
        date_next = datetime.datetime.strptime(row_next["time"], date_format_string)
        wait_time = (date_next - date_now).total_seconds()
        
        row_now_index = indices[i]
        # write to the original dataset
        # pd_all_data.loc[row_now_index]['wait_time'] = wait_time
        pd_all_data.at[row_now_index,'wait_time'] = wait_time

In [ ]:

# for calculating wait_time for bike arriving
pd_all_data = stations_dict_all["key"]
for sn in station_names:
    station_data = pd_all_data[pd_all_data['station']==sn]
    station_data = station_data[station_data['decrement'] == 1]    
    
    for i in range(len(station_data)-2):
        row_now = station_data.iloc[i]
        row_next = station_data.iloc[i+1]
        date_now = datetime.datetime.strptime(row_now["time"], date_format_string)
        date_next = datetime.datetime.strptime(row_next["time"], date_format_string)
        wait_time = (date_next - date_now).total_seconds()
        
        row_now['wait_time'] = wait_time

In [191]:
stations_dict_all["key"]['wait_time'] = 0

In [202]:
pd_all_data[pd_all_data['station']=="1200 Beacon St"]

,time,capacity,station,increment,decrement,wait_time,year,month,day_of_week,day,hour,minute,second
225,2021-09-01 00:07:38.0940,14,1200 Beacon St,0,1,0,2021,9,Wednesday,1,0,7,38
267,2021-09-01 00:09:02.4160,13,1200 Beacon St,0,1,0,2021,9,Wednesday,1,0,9,2
459,2021-09-01 00:30:10.0210,14,1200 Beacon St,1,0,2981,2021,9,Wednesday,1,0,30,10
1658,2021-09-01 01:12:53.7920,14,1200 Beacon St,0,1,0,2021,9,Wednesday,1,1,12,53
1662,2021-09-01 01:13:11.5040,13,1200 Beacon St,0,1,0,2021,9,Wednesday,1,1,13,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859546,2021-09-30 22:49:07.5880,-5,1200 Beacon St,1,0,690,2021,9,Thursday,30,22,49,7
860086,2021-09-30 23:00:37.6920,-3,1200 Beacon St,1,0,958,2021,9,Thursday,30,23,0,37
860339,2021-09-30 23:16:36.3850,-2,1200 Beacon St,1,0,6277,2021,9,Thursday,30,23,16,36
861555,2021-09-30 23:37:08.5160,-3,1200 Beacon St,0,1,0,2021,9,Thursday,30,23,37,8
862093,2021-10-01 01:01:13.6380,-2,1200 Beacon St,1,0,0,2021,10,Friday,1,1,1,13

In [201]:
pd_all_data.to_csv('202109-stations-capacity/all_data.csv', index=False)